aruco_node_cpp:
  ros__parameters:
    publish_debug: true
    marker_size: 0.05
    camera_frame: "head_camera_infra1_optical_frame"
    aruco_dictionary_id: "DICT_APRILTAG_36h11"
    filter_min_cutoff: 1.0
    filter_beta: 0.05